# ==========================================
# Script 2: Jiayi's Task (Overall EDA & Normality Check)
# Recommended Location: Inside the code/ folder of the GitHub repository
# ==========================================

library(ggplot2)

# 1. Read the cleaned data subset generated by the data cleaning script
# Ensure "sydney_rainfall_1968_1998.csv" is in the current working directory
if (!file.exists("sydney_rainfall_1968_1998.csv")) {
  stop("Cannot find the cleaned data file 'sydney_rainfall_1968_1998.csv'. Please run the data cleaning script first!")
}

cleaned_data <- read.csv("sydney_rainfall_1968_1998.csv")

# Extract a 1D vector of overall rainfall data (excluding NA values)
df_overall <- data.frame(Rainfall = cleaned_data$Rainfall[!is.na(cleaned_data$Rainfall)])

# 2. Generate summary statistics
print("=== Jiayi's Summary Statistics ===")
summary(df_overall$Rainfall)
print(paste("IQR:", IQR(df_overall$Rainfall)))

# 3. Generate and automatically save the overall boxplot -> save to output/ folder
png("Jiayi_Overall_Boxplot.png", width = 800, height = 600)
boxplot(df_overall$Rainfall, 
        main = "Overall Boxplot of Monthly Rainfall (1968-1998)",
        ylab = "Rainfall (millimetres)",
        col = "lightblue")
dev.off()

# 4. Generate and automatically save the overall Normal Q-Q Plot (Assumption Checking) -> save to output/ folder
qq_plot <- ggplot(df_overall, aes(sample = Rainfall)) +
  stat_qq_line(distribution = stats::qnorm, color = "red", linewidth = 1) +
  stat_qq(distribution = stats::qnorm, size = 1.5) +
  labs(x = "Theoretical Quantiles", y = "Sample Quantiles", title = "Overall Normal Q-Q Plot for Monthly Rainfall") +
  theme_bw()

ggsave("Jiayi_Overall_QQplot.png", plot = qq_plot, width = 8, height = 6, dpi = 300)

cat("[Analysis Completed] Your exclusive charts Jiayi_Overall_Boxplot.png and Jiayi_Overall_QQplot.png have been successfully generated!\n")
